### ISSUE TITLE
Installation Section

### ISSUE THREAD

**Issue by lfarah** [lorentey/GlueKit#1]
Hey, your library is really interesting.

The only problem I found was the `README.md`, which lacks an `Installation Section`
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an `Installation Section`
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by lorentey** [comment]
I agree it's crazy hard to set up GlueKit right now, especially with the included project file. I was just looking for a template for an installation section, thank you!

**Comment by lfarah** [comment]
You're welcome! 😉

**Comment by lorentey** [comment]
I added an installation section to the README, and I also made it much easier to start using GlueKit. Please file bugs if it could be made even smoother!

Thank you :-)
